language: python
python:
  - "3.7.0"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov
  - pip install coveralls
script:
  - python Code/item_testcases.py
  - python Code/user_testcases.py
  - python Code/ensemble_testcases.py 
  - cd Code; pytest ensemble.py; 
  - coverage run -m py.test ensemble.py; coverage report --omit="*/home/*,*urls.py"; cd ..
after_success:
  - bash <(curl -s https://codecov.io/bash)
